//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FavLinkModel", "FK_TBL_LINK_REFERENCE_TBL_CATE", "tbl_category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FavLink.Entity.tbl_category), "tbl_link_data", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FavLink.Entity.tbl_link_data), true)]
[assembly: EdmRelationshipAttribute("FavLinkModel", "FK_TBL_ITSU_REFERENCE_TBL_ITSU", "tbl_itsupport", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FavLink.Entity.tbl_itsupport), "tbl_itsupport_arrangment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FavLink.Entity.tbl_itsupport_arrangment), true)]
[assembly: EdmRelationshipAttribute("FavLinkModel", "FK_TBL_LINK_REFERENCE_TBL_USER", "tbl_user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FavLink.Entity.tbl_user), "tbl_link_data", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FavLink.Entity.tbl_link_data), true)]

#endregion

namespace FavLink.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FavLinkEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FavLinkEntities object using the connection string found in the 'FavLinkEntities' section of the application configuration file.
        /// </summary>
        public FavLinkEntities() : base("name=FavLinkEntities", "FavLinkEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FavLinkEntities object.
        /// </summary>
        public FavLinkEntities(string connectionString) : base(connectionString, "FavLinkEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FavLinkEntities object.
        /// </summary>
        public FavLinkEntities(EntityConnection connection) : base(connection, "FavLinkEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_category> tbl_category
        {
            get
            {
                if ((_tbl_category == null))
                {
                    _tbl_category = base.CreateObjectSet<tbl_category>("tbl_category");
                }
                return _tbl_category;
            }
        }
        private ObjectSet<tbl_category> _tbl_category;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_itsupport> tbl_itsupport
        {
            get
            {
                if ((_tbl_itsupport == null))
                {
                    _tbl_itsupport = base.CreateObjectSet<tbl_itsupport>("tbl_itsupport");
                }
                return _tbl_itsupport;
            }
        }
        private ObjectSet<tbl_itsupport> _tbl_itsupport;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_itsupport_arrangment> tbl_itsupport_arrangment
        {
            get
            {
                if ((_tbl_itsupport_arrangment == null))
                {
                    _tbl_itsupport_arrangment = base.CreateObjectSet<tbl_itsupport_arrangment>("tbl_itsupport_arrangment");
                }
                return _tbl_itsupport_arrangment;
            }
        }
        private ObjectSet<tbl_itsupport_arrangment> _tbl_itsupport_arrangment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_link_data> tbl_link_data
        {
            get
            {
                if ((_tbl_link_data == null))
                {
                    _tbl_link_data = base.CreateObjectSet<tbl_link_data>("tbl_link_data");
                }
                return _tbl_link_data;
            }
        }
        private ObjectSet<tbl_link_data> _tbl_link_data;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_user> tbl_user
        {
            get
            {
                if ((_tbl_user == null))
                {
                    _tbl_user = base.CreateObjectSet<tbl_user>("tbl_user");
                }
                return _tbl_user;
            }
        }
        private ObjectSet<tbl_user> _tbl_user;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_hotline> tbl_hotline
        {
            get
            {
                if ((_tbl_hotline == null))
                {
                    _tbl_hotline = base.CreateObjectSet<tbl_hotline>("tbl_hotline");
                }
                return _tbl_hotline;
            }
        }
        private ObjectSet<tbl_hotline> _tbl_hotline;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_category EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_category(tbl_category tbl_category)
        {
            base.AddObject("tbl_category", tbl_category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_itsupport EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_itsupport(tbl_itsupport tbl_itsupport)
        {
            base.AddObject("tbl_itsupport", tbl_itsupport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_itsupport_arrangment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_itsupport_arrangment(tbl_itsupport_arrangment tbl_itsupport_arrangment)
        {
            base.AddObject("tbl_itsupport_arrangment", tbl_itsupport_arrangment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_link_data EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_link_data(tbl_link_data tbl_link_data)
        {
            base.AddObject("tbl_link_data", tbl_link_data);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_user EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_user(tbl_user tbl_user)
        {
            base.AddObject("tbl_user", tbl_user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_hotline EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_hotline(tbl_hotline tbl_hotline)
        {
            base.AddObject("tbl_hotline", tbl_hotline);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FavLinkModel", Name="tbl_category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_category object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static tbl_category Createtbl_category(global::System.Int32 id, global::System.String name)
        {
            tbl_category tbl_category = new tbl_category();
            tbl_category.id = id;
            tbl_category.name = name;
            return tbl_category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FavLinkModel", "FK_TBL_LINK_REFERENCE_TBL_CATE", "tbl_link_data")]
        public EntityCollection<tbl_link_data> tbl_link_data
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_link_data>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_CATE", "tbl_link_data");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_link_data>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_CATE", "tbl_link_data", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FavLinkModel", Name="tbl_hotline")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_hotline : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_hotline object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static tbl_hotline Createtbl_hotline(global::System.Int32 id, global::System.String name)
        {
            tbl_hotline tbl_hotline = new tbl_hotline();
            tbl_hotline.id = id;
            tbl_hotline.name = name;
            return tbl_hotline;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone_number
        {
            get
            {
                return _phone_number;
            }
            set
            {
                Onphone_numberChanging(value);
                ReportPropertyChanging("phone_number");
                _phone_number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone_number");
                Onphone_numberChanged();
            }
        }
        private global::System.String _phone_number;
        partial void Onphone_numberChanging(global::System.String value);
        partial void Onphone_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private Nullable<global::System.Int32> _category;
        partial void OncategoryChanging(Nullable<global::System.Int32> value);
        partial void OncategoryChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FavLinkModel", Name="tbl_itsupport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_itsupport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_itsupport object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static tbl_itsupport Createtbl_itsupport(global::System.Int32 id, global::System.String name)
        {
            tbl_itsupport tbl_itsupport = new tbl_itsupport();
            tbl_itsupport.id = id;
            tbl_itsupport.name = name;
            return tbl_itsupport;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone_number
        {
            get
            {
                return _phone_number;
            }
            set
            {
                Onphone_numberChanging(value);
                ReportPropertyChanging("phone_number");
                _phone_number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone_number");
                Onphone_numberChanged();
            }
        }
        private global::System.String _phone_number;
        partial void Onphone_numberChanging(global::System.String value);
        partial void Onphone_numberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FavLinkModel", "FK_TBL_ITSU_REFERENCE_TBL_ITSU", "tbl_itsupport_arrangment")]
        public EntityCollection<tbl_itsupport_arrangment> tbl_itsupport_arrangment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_itsupport_arrangment>("FavLinkModel.FK_TBL_ITSU_REFERENCE_TBL_ITSU", "tbl_itsupport_arrangment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_itsupport_arrangment>("FavLinkModel.FK_TBL_ITSU_REFERENCE_TBL_ITSU", "tbl_itsupport_arrangment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FavLinkModel", Name="tbl_itsupport_arrangment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_itsupport_arrangment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_itsupport_arrangment object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="ref_personID">Initial value of the ref_personID property.</param>
        public static tbl_itsupport_arrangment Createtbl_itsupport_arrangment(global::System.Int32 id, global::System.Int32 ref_personID)
        {
            tbl_itsupport_arrangment tbl_itsupport_arrangment = new tbl_itsupport_arrangment();
            tbl_itsupport_arrangment.id = id;
            tbl_itsupport_arrangment.ref_personID = ref_personID;
            return tbl_itsupport_arrangment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ref_personID
        {
            get
            {
                return _ref_personID;
            }
            set
            {
                Onref_personIDChanging(value);
                ReportPropertyChanging("ref_personID");
                _ref_personID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_personID");
                Onref_personIDChanged();
            }
        }
        private global::System.Int32 _ref_personID;
        partial void Onref_personIDChanging(global::System.Int32 value);
        partial void Onref_personIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String project
        {
            get
            {
                return _project;
            }
            set
            {
                OnprojectChanging(value);
                ReportPropertyChanging("project");
                _project = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("project");
                OnprojectChanged();
            }
        }
        private global::System.String _project;
        partial void OnprojectChanging(global::System.String value);
        partial void OnprojectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> shift
        {
            get
            {
                return _shift;
            }
            set
            {
                OnshiftChanging(value);
                ReportPropertyChanging("shift");
                _shift = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("shift");
                OnshiftChanged();
            }
        }
        private Nullable<global::System.Int32> _shift;
        partial void OnshiftChanging(Nullable<global::System.Int32> value);
        partial void OnshiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> month
        {
            get
            {
                return _month;
            }
            set
            {
                OnmonthChanging(value);
                ReportPropertyChanging("month");
                _month = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("month");
                OnmonthChanged();
            }
        }
        private Nullable<global::System.Int32> _month;
        partial void OnmonthChanging(Nullable<global::System.Int32> value);
        partial void OnmonthChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FavLinkModel", "FK_TBL_ITSU_REFERENCE_TBL_ITSU", "tbl_itsupport")]
        public tbl_itsupport tbl_itsupport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_itsupport>("FavLinkModel.FK_TBL_ITSU_REFERENCE_TBL_ITSU", "tbl_itsupport").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_itsupport>("FavLinkModel.FK_TBL_ITSU_REFERENCE_TBL_ITSU", "tbl_itsupport").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_itsupport> tbl_itsupportReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_itsupport>("FavLinkModel.FK_TBL_ITSU_REFERENCE_TBL_ITSU", "tbl_itsupport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_itsupport>("FavLinkModel.FK_TBL_ITSU_REFERENCE_TBL_ITSU", "tbl_itsupport", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FavLinkModel", Name="tbl_link_data")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_link_data : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_link_data object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tbl_link_data Createtbl_link_data(global::System.Int32 id)
        {
            tbl_link_data tbl_link_data = new tbl_link_data();
            tbl_link_data.id = id;
            return tbl_link_data;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ref_userID
        {
            get
            {
                return _ref_userID;
            }
            set
            {
                Onref_userIDChanging(value);
                ReportPropertyChanging("ref_userID");
                _ref_userID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_userID");
                Onref_userIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ref_userID;
        partial void Onref_userIDChanging(Nullable<global::System.Int32> value);
        partial void Onref_userIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ref_categoryID
        {
            get
            {
                return _ref_categoryID;
            }
            set
            {
                Onref_categoryIDChanging(value);
                ReportPropertyChanging("ref_categoryID");
                _ref_categoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ref_categoryID");
                Onref_categoryIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ref_categoryID;
        partial void Onref_categoryIDChanging(Nullable<global::System.Int32> value);
        partial void Onref_categoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String icon
        {
            get
            {
                return _icon;
            }
            set
            {
                OniconChanging(value);
                ReportPropertyChanging("icon");
                _icon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("icon");
                OniconChanged();
            }
        }
        private global::System.String _icon;
        partial void OniconChanging(global::System.String value);
        partial void OniconChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bg_color
        {
            get
            {
                return _bg_color;
            }
            set
            {
                Onbg_colorChanging(value);
                ReportPropertyChanging("bg_color");
                _bg_color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bg_color");
                Onbg_colorChanged();
            }
        }
        private global::System.String _bg_color;
        partial void Onbg_colorChanging(global::System.String value);
        partial void Onbg_colorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FavLinkModel", "FK_TBL_LINK_REFERENCE_TBL_CATE", "tbl_category")]
        public tbl_category tbl_category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_category>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_CATE", "tbl_category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_category>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_CATE", "tbl_category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_category> tbl_categoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_category>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_CATE", "tbl_category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_category>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_CATE", "tbl_category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FavLinkModel", "FK_TBL_LINK_REFERENCE_TBL_USER", "tbl_user")]
        public tbl_user tbl_user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_USER", "tbl_user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_USER", "tbl_user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_user> tbl_userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_USER", "tbl_user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_user>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_USER", "tbl_user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FavLinkModel", Name="tbl_user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_user object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="aDAccount">Initial value of the ADAccount property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="isValid">Initial value of the IsValid property.</param>
        /// <param name="isAdmin">Initial value of the IsAdmin property.</param>
        /// <param name="fullName">Initial value of the FullName property.</param>
        public static tbl_user Createtbl_user(global::System.Int32 id, global::System.String aDAccount, global::System.String email, global::System.Boolean isValid, global::System.Boolean isAdmin, global::System.String fullName)
        {
            tbl_user tbl_user = new tbl_user();
            tbl_user.id = id;
            tbl_user.ADAccount = aDAccount;
            tbl_user.Email = email;
            tbl_user.IsValid = isValid;
            tbl_user.IsAdmin = isAdmin;
            tbl_user.FullName = fullName;
            return tbl_user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ADAccount
        {
            get
            {
                return _ADAccount;
            }
            set
            {
                OnADAccountChanging(value);
                ReportPropertyChanging("ADAccount");
                _ADAccount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ADAccount");
                OnADAccountChanged();
            }
        }
        private global::System.String _ADAccount;
        partial void OnADAccountChanging(global::System.String value);
        partial void OnADAccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLogon
        {
            get
            {
                return _LastLogon;
            }
            set
            {
                OnLastLogonChanging(value);
                ReportPropertyChanging("LastLogon");
                _LastLogon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogon");
                OnLastLogonChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLogon;
        partial void OnLastLogonChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLogonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsValid
        {
            get
            {
                return _IsValid;
            }
            set
            {
                OnIsValidChanging(value);
                ReportPropertyChanging("IsValid");
                _IsValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValid");
                OnIsValidChanged();
            }
        }
        private global::System.Boolean _IsValid;
        partial void OnIsValidChanging(global::System.Boolean value);
        partial void OnIsValidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdmin
        {
            get
            {
                return _IsAdmin;
            }
            set
            {
                OnIsAdminChanging(value);
                ReportPropertyChanging("IsAdmin");
                _IsAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdmin");
                OnIsAdminChanged();
            }
        }
        private global::System.Boolean _IsAdmin;
        partial void OnIsAdminChanging(global::System.Boolean value);
        partial void OnIsAdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FavLinkModel", "FK_TBL_LINK_REFERENCE_TBL_USER", "tbl_link_data")]
        public EntityCollection<tbl_link_data> tbl_link_data
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_link_data>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_USER", "tbl_link_data");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_link_data>("FavLinkModel.FK_TBL_LINK_REFERENCE_TBL_USER", "tbl_link_data", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
