//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FavLink.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FavLinkEntities : DbContext
    {
        public FavLinkEntities()
            : base("name=FavLinkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_itsupport> tbl_itsupport { get; set; }
        public virtual DbSet<tbl_itsupport_arrangment> tbl_itsupport_arrangment { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_link_data> tbl_link_data { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
