//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FavLink.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_itsupport_arrangment
    {
        public int id { get; set; }
        public int ref_personID { get; set; }
        public string project { get; set; }
        public Nullable<int> shift { get; set; }
        public Nullable<int> month { get; set; }
    
        public virtual tbl_itsupport tbl_itsupport { get; set; }
    }
}
