//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FavLink.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_link_data
    {
        public int id { get; set; }
        public Nullable<int> ref_userID { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<int> ref_categoryID { get; set; }
        public string icon { get; set; }
        public string bg_color { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
